#! /bin/sh

if [ -z $1 ]; then
language=python
else
language=$1
fi

GIT_FOLDER=$(git rev-parse --git-dir)
PROJECT_ROOT_FOLDER=$(git rev-parse --show-toplevel)
TMP_FILES=$GIT_FOLDER/files
TMP_FILES_CSCOPE=$GIT_FOLDER/cscope_files

echo 'Remove old tags file...'
rm -f $GIT_FOLDER/tags
rm -f $GIT_FOLDER/cscope.*

git ls-files | while IFS= read -r file
do
    [ -f "$PROJECT_ROOT_FOLDER/$file" ] && [ ! -L "$PROJECT_ROOT_FOLDER/$file" ] || continue
    echo "$PROJECT_ROOT_FOLDER/$file" >> $TMP_FILES
    case "$file" in
        *\ *) ;;
        *) echo "$file" >> $TMP_FILES_CSCOPE ;;
    esac
done

echo 'Generate tags file'
ctags -L $TMP_FILES --fields=iaS --extras=+q -f "$GIT_FOLDER/$$.tags"
mv $GIT_FOLDER/$$.tags $GIT_FOLDER/tags

(cd "$PROJECT_ROOT_FOLDER" && cscope -bkq -i "$TMP_FILES_CSCOPE" && mv cscope.* "$GIT_FOLDER")

rm $TMP_FILES $TMP_FILES_CSCOPE
echo 'Generate completed...'
