#! /bin/sh

if [ -z $1 ]; then
language=python
else
language=$1
fi

GIT_FOLDER=$(git rev-parse --git-dir)
PROJECT_ROOT_FOLDER=$(git rev-parse --show-toplevel)
TMP_FILES=$GIT_FOLDER/files

echo 'Remove old tags file...'
rm -f $GIT_FOLDER/tags
rm -f $GIT_FOLDER/cscope.*

for file in $(git ls-files)
do
    echo $PROJECT_ROOT_FOLDER/$file >> $TMP_FILES
done

echo 'Generate tags file'
ctags -L $TMP_FILES --fields=iaS --extra=+q -f "$GIT_FOLDER/$$.tags"
mv $GIT_FOLDER/$$.tags $GIT_FOLDER/tags

cscope -Rbkq -i $TMP_FILES
mv cscope.* $GIT_FOLDER
rm $TMP_FILES
echo 'Generate completed...'

